AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions: #array of properties
      - AttributeName: id #name and type are object or an array item
        AttributeType: S  #String
    KeySchema: #here i say that attribute with name id should be hash of the table
      - AttributeName: id
        KeyType: HASH